p8105_hw2_jr4550
================
Jeff Remo
2025-10-01

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.2     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

### Problem 1

First, clean the data in pols-month.csv.

``` r
pols_df = 
  read_csv("data/pols-month.csv", na = c("NA", ".", "")) %>% 
  janitor::clean_names() %>% 
  separate(mon, into = c("year", "month", "date"), sep = "-", convert = TRUE) %>% 
  mutate(
    month = month.name[month], 
    president = case_when(
      prez_gop == 1 ~ "gop",
      prez_dem == 1 ~ "dem"
    )) %>% 
  select(-prez_gop, -prez_dem)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Clean the snp.csv

``` r
snp_df = 
  read_csv("data/snp.csv", na = c("NA", ".", "")) %>% 
  janitor::clean_names() %>%
  separate(date, into = c("month", "day", "year"), sep = "/", convert = TRUE) %>%
  mutate(
    month = month.name[month],
    year = if_else(year < 50, year + 2000, year + 1900)
  ) %>%
  select(year, month, close)
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

clean the unemployment

``` r
unemployment_df = 
  read_csv("data/unemployment.csv", na = c("NA", ".","")) %>% 
  janitor::clean_names() %>% 
   pivot_longer(
    cols = jan:dec,
    names_to = "month",
    values_to = "unemployment_pct"
  ) |>
  mutate(
    year = as.integer(year),
    month = factor(month,
                   levels = tolower(month.abb),
                   labels = month.name),
    month = as.character(month)
  )
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Joining data sets

``` r
merged_df = pols_df %>%
  left_join(snp_df, by = c("year", "month")) %>%
  left_join(unemployment_df, by = c("year", "month")) %>% 
  select(-date)
```

#### Description of Problem 1 datasets

The pols_df dataset characterizes the the political party representation
of the number of Senators (“sen_dem & sen_gop) and Representatives
(rep_gop & rep_dem), and the political party of the President (dem/gop)
in the United States over from 1947-2015. The snp_df shows the S&P
values of each month from Dec 1950- July 2015. The unemployment_df shows
the unemployments rates in the US from Jan 1948-June2015.

### Problem 2

Read and clean Mr.Trashwheel Dataset

``` r
library(tidyverse)
library(readxl)

mr_trashwheeldf = 
  read_excel("data/202509 Trash Wheel Collection Data.xlsx", 
             sheet = "Mr. Trash Wheel",
             range = "A2:N586") %>%
  janitor::clean_names() %>%
  filter(!is.na(dumpster)) %>%
  mutate(
    sports_balls = as.integer(round(sports_balls)),
    trash_wheel = "Mr. Trash Wheel",
    year = as.numeric(year)
  )

prof_trashwheel_df = 
  read_excel("data/202509 Trash Wheel Collection Data.xlsx", 
             sheet = "Professor Trash Wheel",
             range = "A2:M108") %>%
  janitor::clean_names() %>%
  filter(!is.na(dumpster)) %>%
  mutate(
    trash_wheel = "Professor Trash Wheel",
    year = as.numeric(year)
  )

gwynnda_df = 
  read_excel("data/202509 Trash Wheel Collection Data.xlsx", 
             sheet = "Gwynns Falls Trash Wheel",
             range = "A2:L157") %>%
  janitor::clean_names() %>%
  filter(!is.na(dumpster)) %>%
  mutate(
    trash_wheel = "Gwynns Falls Trash Wheel",
    year = as.numeric(year)
  )

trash_wheel_df = 
  bind_rows(mr_trashwheeldf, prof_trashwheel_df, gwynnda_df)

prof_total_weight = prof_trashwheel_df %>%
  summarize(total_weight = sum(weight_tons, na.rm = TRUE)) %>%
  pull(total_weight)

gwynnda_june_2022_cigs = gwynnda_df %>%
  filter(month == "June", year == 2022) %>%
  summarize(total_cigs = sum(cigarette_butts, na.rm = TRUE)) %>%
  pull(total_cigs)
```

``` r
format(prof_total_weight, nsmall = 2)
```

    ## [1] "216.26"

``` r
format(gwynnda_june_2022_cigs, big.mark = ",")
```

    ## [1] "18,120"

#### Description of Trash Wheel Dataset

The combined Trash Wheel dataset contains r nrow(trashwheel_df)
observations from three water-wheel trash collectors in Baltimore’s
Inner Harbor. Key variables include date, weight_tons,
volume_cubic_yards, and counts of specific items like plastic_bottles,
cigarette_butts, and sports_balls. Professor Trash Wheel collected a
total of 216.26 tons of trash. In June 2022, Gwynnda collected 18,120
cigarette butts.

### Problem 3
